import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting seed...');

  // ============================================================================
  // 1. CREATE ADMIN USER
  // ============================================================================
  const hashedPassword = await bcrypt.hash('admin123', 10);
  
  const admin = await prisma.user.upsert({
    where: { email: 'admin@speisenreise.de' },
    update: {},
    create: {
      email: 'admin@speisenreise.de',
      emailVerified: true,
      firstName: 'Admin',
      lastName: 'User',
      phone: '+491234567890',
      passwordHash: hashedPassword,
    },
  });
  console.log('✅ Admin user created:', admin.email);

  // ============================================================================
  // 2. CREATE CATEGORIES
  // ============================================================================
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { id: 'pizza' },
      update: {},
      create: {
        id: 'pizza',
        name: 'Pizza',
        nameDe: 'Pizza',
        description: 'Authentic Italian pizzas',
        descriptionDe: 'Authentische italienische Pizzen',
        sortOrder: 1,
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { id: 'burger' },
      update: {},
      create: {
        id: 'burger',
        name: 'Burger',
        nameDe: 'Burger',
        description: 'Juicy burgers with fresh ingredients',
        descriptionDe: 'Saftige Burger mit frischen Zutaten',
        sortOrder: 2,
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { id: 'doener' },
      update: {},
      create: {
        id: 'doener',
        name: 'Döner',
        nameDe: 'Döner',
        description: 'Traditional Turkish döner kebab',
        descriptionDe: 'Traditioneller türkischer Döner Kebab',
        sortOrder: 3,
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { id: 'pasta' },
      update: {},
      create: {
        id: 'pasta',
        name: 'Pasta',
        nameDe: 'Pasta',
        description: 'Fresh pasta dishes',
        descriptionDe: 'Frische Pasta-Gerichte',
        sortOrder: 4,
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { id: 'salads' },
      update: {},
      create: {
        id: 'salads',
        name: 'Salads',
        nameDe: 'Salate',
        description: 'Fresh and healthy salads',
        descriptionDe: 'Frische und gesunde Salate',
        sortOrder: 5,
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { id: 'desserts' },
      update: {},
      create: {
        id: 'desserts',
        name: 'Desserts',
        nameDe: 'Desserts',
        description: 'Sweet treats and desserts',
        descriptionDe: 'Süße Leckereien und Desserts',
        sortOrder: 6,
        isActive: true,
      },
    }),
    prisma.category.upsert({
      where: { id: 'drinks' },
      update: {},
      create: {
        id: 'drinks',
        name: 'Drinks',
        nameDe: 'Getränke',
        description: 'Refreshing beverages',
        descriptionDe: 'Erfrischende Getränke',
        sortOrder: 7,
        isActive: true,
      },
    }),
  ]);
  console.log('✅ Categories created:', categories.length);

  // ============================================================================
  // 3. CREATE PRODUCTS
  // ============================================================================
  
  // Pizza Products
  const pizzaCategory = categories.find(c => c.id === 'pizza')!;
  const pizzas = await Promise.all([
    prisma.product.upsert({
      where: { id: 'pizza-margherita' },
      update: {},
      create: {
        id: 'pizza-margherita',
        categoryId: pizzaCategory.id,
        name: 'Margherita',
        nameDe: 'Margherita',
        description: 'Classic pizza with tomato sauce, mozzarella, and fresh basil',
        descriptionDe: 'Klassische Pizza mit Tomatensauce, Mozzarella und frischem Basilikum',
        price: 8.50,
        sortOrder: 1,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 850,
        allergens: ['Gluten', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pizza-salami' },
      update: {},
      create: {
        id: 'pizza-salami',
        categoryId: pizzaCategory.id,
        name: 'Salami',
        nameDe: 'Salami',
        description: 'Tomato sauce, mozzarella, and spicy salami',
        descriptionDe: 'Tomatensauce, Mozzarella und scharfe Salami',
        price: 9.50,
        sortOrder: 2,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 950,
        allergens: ['Gluten', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pizza-prosciutto' },
      update: {},
      create: {
        id: 'pizza-prosciutto',
        categoryId: pizzaCategory.id,
        name: 'Prosciutto',
        nameDe: 'Prosciutto',
        description: 'Tomato sauce, mozzarella, and cooked ham',
        descriptionDe: 'Tomatensauce, Mozzarella und gekochter Schinken',
        price: 10.00,
        sortOrder: 3,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 900,
        allergens: ['Gluten', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pizza-tonno' },
      update: {},
      create: {
        id: 'pizza-tonno',
        categoryId: pizzaCategory.id,
        name: 'Tonno',
        nameDe: 'Tonno',
        description: 'Tomato sauce, mozzarella, tuna, and onions',
        descriptionDe: 'Tomatensauce, Mozzarella, Thunfisch und Zwiebeln',
        price: 11.00,
        sortOrder: 4,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 920,
        allergens: ['Gluten', 'Milk', 'Fish'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pizza-quattro-formaggi' },
      update: {},
      create: {
        id: 'pizza-quattro-formaggi',
        categoryId: pizzaCategory.id,
        name: 'Quattro Formaggi',
        nameDe: 'Vier Käse',
        description: 'Four cheese pizza with mozzarella, gorgonzola, parmesan, and emmental',
        descriptionDe: 'Vier-Käse-Pizza mit Mozzarella, Gorgonzola, Parmesan und Emmental',
        price: 12.50,
        sortOrder: 5,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 1100,
        allergens: ['Gluten', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pizza-hawaii' },
      update: {},
      create: {
        id: 'pizza-hawaii',
        categoryId: pizzaCategory.id,
        name: 'Hawaii',
        nameDe: 'Hawaii',
        description: 'Tomato sauce, mozzarella, ham, and pineapple',
        descriptionDe: 'Tomatensauce, Mozzarella, Schinken und Ananas',
        price: 10.50,
        sortOrder: 6,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 980,
        allergens: ['Gluten', 'Milk'],
      },
    }),
  ]);
  console.log('✅ Pizzas created:', pizzas.length);

  // Burger Products
  const burgerCategory = categories.find(c => c.id === 'burger')!;
  const burgers = await Promise.all([
    prisma.product.upsert({
      where: { id: 'burger-classic' },
      update: {},
      create: {
        id: 'burger-classic',
        categoryId: burgerCategory.id,
        name: 'Classic Burger',
        nameDe: 'Klassischer Burger',
        description: 'Beef patty, lettuce, tomato, onion, pickles, and special sauce',
        descriptionDe: 'Rindfleisch-Patty, Salat, Tomate, Zwiebeln, Gewürzgurken und spezielle Sauce',
        price: 9.90,
        sortOrder: 1,
        isActive: true,
        isAvailable: true,
        preparationTime: 12,
        calories: 750,
        allergens: ['Gluten', 'Eggs', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'burger-cheese' },
      update: {},
      create: {
        id: 'burger-cheese',
        categoryId: burgerCategory.id,
        name: 'Cheeseburger',
        nameDe: 'Cheeseburger',
        description: 'Beef patty, cheddar cheese, lettuce, tomato, and onion',
        descriptionDe: 'Rindfleisch-Patty, Cheddar-Käse, Salat, Tomate und Zwiebeln',
        price: 10.90,
        sortOrder: 2,
        isActive: true,
        isAvailable: true,
        preparationTime: 12,
        calories: 820,
        allergens: ['Gluten', 'Eggs', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'burger-bacon' },
      update: {},
      create: {
        id: 'burger-bacon',
        categoryId: burgerCategory.id,
        name: 'Bacon Burger',
        nameDe: 'Bacon Burger',
        description: 'Beef patty, crispy bacon, cheddar cheese, and BBQ sauce',
        descriptionDe: 'Rindfleisch-Patty, knuspriger Bacon, Cheddar-Käse und BBQ-Sauce',
        price: 11.90,
        sortOrder: 3,
        isActive: true,
        isAvailable: true,
        preparationTime: 12,
        calories: 950,
        allergens: ['Gluten', 'Eggs', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'burger-chicken' },
      update: {},
      create: {
        id: 'burger-chicken',
        categoryId: burgerCategory.id,
        name: 'Chicken Burger',
        nameDe: 'Hähnchen Burger',
        description: 'Crispy chicken breast, lettuce, tomato, and mayo',
        descriptionDe: 'Knuspriges Hähnchenbrust, Salat, Tomate und Mayo',
        price: 9.50,
        sortOrder: 4,
        isActive: true,
        isAvailable: true,
        preparationTime: 12,
        calories: 680,
        allergens: ['Gluten', 'Eggs', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'burger-veggie' },
      update: {},
      create: {
        id: 'burger-veggie',
        categoryId: burgerCategory.id,
        name: 'Veggie Burger',
        nameDe: 'Veggie Burger',
        description: 'Plant-based patty, lettuce, tomato, onion, and vegan mayo',
        descriptionDe: 'Pflanzliches Patty, Salat, Tomate, Zwiebeln und vegane Mayo',
        price: 10.50,
        sortOrder: 5,
        isActive: true,
        isAvailable: true,
        preparationTime: 12,
        calories: 520,
        allergens: ['Gluten', 'Sesame', 'Soybeans'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'burger-double' },
      update: {},
      create: {
        id: 'burger-double',
        categoryId: burgerCategory.id,
        name: 'Double Burger',
        nameDe: 'Doppel Burger',
        description: 'Two beef patties, double cheese, lettuce, tomato, and special sauce',
        descriptionDe: 'Zwei Rindfleisch-Pattys, doppelter Käse, Salat, Tomate und spezielle Sauce',
        price: 13.90,
        sortOrder: 6,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 1200,
        allergens: ['Gluten', 'Eggs', 'Milk', 'Sesame'],
      },
    }),
  ]);
  console.log('✅ Burgers created:', burgers.length);

  // Döner Products
  const doenerCategory = categories.find(c => c.id === 'doener')!;
  const doeners = await Promise.all([
    prisma.product.upsert({
      where: { id: 'doener-classic' },
      update: {},
      create: {
        id: 'doener-classic',
        categoryId: doenerCategory.id,
        name: 'Döner Kebab',
        nameDe: 'Döner Kebab',
        description: 'Traditional döner with meat, vegetables, and sauce in flatbread',
        descriptionDe: 'Traditioneller Döner mit Fleisch, Gemüse und Sauce im Fladenbrot',
        price: 7.50,
        sortOrder: 1,
        isActive: true,
        isAvailable: true,
        preparationTime: 10,
        calories: 850,
        allergens: ['Gluten', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'doener-chicken' },
      update: {},
      create: {
        id: 'doener-chicken',
        categoryId: doenerCategory.id,
        name: 'Chicken Döner',
        nameDe: 'Hähnchen Döner',
        description: 'Chicken döner with vegetables and sauce',
        descriptionDe: 'Hähnchen Döner mit Gemüse und Sauce',
        price: 7.00,
        sortOrder: 2,
        isActive: true,
        isAvailable: true,
        preparationTime: 10,
        calories: 720,
        allergens: ['Gluten', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'doener-vegetarian' },
      update: {},
      create: {
        id: 'doener-vegetarian',
        categoryId: doenerCategory.id,
        name: 'Vegetarian Döner',
        nameDe: 'Vegetarischer Döner',
        description: 'Vegetarian döner with falafel, vegetables, and sauce',
        descriptionDe: 'Vegetarischer Döner mit Falafel, Gemüse und Sauce',
        price: 7.00,
        sortOrder: 3,
        isActive: true,
        isAvailable: true,
        preparationTime: 10,
        calories: 650,
        allergens: ['Gluten', 'Milk', 'Sesame', 'Soybeans'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'doener-special' },
      update: {},
      create: {
        id: 'doener-special',
        categoryId: doenerCategory.id,
        name: 'Döner Special',
        nameDe: 'Döner Special',
        description: 'Döner with extra meat, cheese, and special sauce',
        descriptionDe: 'Döner mit extra Fleisch, Käse und spezieller Sauce',
        price: 9.00,
        sortOrder: 4,
        isActive: true,
        isAvailable: true,
        preparationTime: 10,
        calories: 1050,
        allergens: ['Gluten', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'doener-spicy' },
      update: {},
      create: {
        id: 'doener-spicy',
        categoryId: doenerCategory.id,
        name: 'Spicy Döner',
        nameDe: 'Scharfer Döner',
        description: 'Döner with spicy sauce and jalapeños',
        descriptionDe: 'Döner mit scharfer Sauce und Jalapeños',
        price: 8.00,
        sortOrder: 5,
        isActive: true,
        isAvailable: true,
        preparationTime: 10,
        calories: 880,
        allergens: ['Gluten', 'Milk', 'Sesame'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'doener-box' },
      update: {},
      create: {
        id: 'doener-box',
        categoryId: doenerCategory.id,
        name: 'Döner Box',
        nameDe: 'Döner Box',
        description: 'Döner meat with rice, salad, and sauce',
        descriptionDe: 'Döner-Fleisch mit Reis, Salat und Sauce',
        price: 9.50,
        sortOrder: 6,
        isActive: true,
        isAvailable: true,
        preparationTime: 10,
        calories: 950,
        allergens: ['Milk', 'Sesame'],
      },
    }),
  ]);
  console.log('✅ Döners created:', doeners.length);

  // Pasta Products
  const pastaCategory = categories.find(c => c.id === 'pasta')!;
  const pastas = await Promise.all([
    prisma.product.upsert({
      where: { id: 'pasta-bolognese' },
      update: {},
      create: {
        id: 'pasta-bolognese',
        categoryId: pastaCategory.id,
        name: 'Spaghetti Bolognese',
        nameDe: 'Spaghetti Bolognese',
        description: 'Spaghetti with rich meat sauce',
        descriptionDe: 'Spaghetti mit fleischhaltiger Tomatensauce',
        price: 10.50,
        sortOrder: 1,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 680,
        allergens: ['Gluten', 'Eggs', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pasta-carbonara' },
      update: {},
      create: {
        id: 'pasta-carbonara',
        categoryId: pastaCategory.id,
        name: 'Spaghetti Carbonara',
        nameDe: 'Spaghetti Carbonara',
        description: 'Spaghetti with bacon, egg, and parmesan',
        descriptionDe: 'Spaghetti mit Speck, Ei und Parmesan',
        price: 11.50,
        sortOrder: 2,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 750,
        allergens: ['Gluten', 'Eggs', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pasta-alfredo' },
      update: {},
      create: {
        id: 'pasta-alfredo',
        categoryId: pastaCategory.id,
        name: 'Fettuccine Alfredo',
        nameDe: 'Fettuccine Alfredo',
        description: 'Fettuccine with creamy alfredo sauce',
        descriptionDe: 'Fettuccine mit cremiger Alfredo-Sauce',
        price: 10.00,
        sortOrder: 3,
        isActive: true,
        isAvailable: true,
        preparationTime: 15,
        calories: 720,
        allergens: ['Gluten', 'Eggs', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pasta-pesto' },
      update: {},
      create: {
        id: 'pasta-pesto',
        categoryId: pastaCategory.id,
        name: 'Penne Pesto',
        nameDe: 'Penne Pesto',
        description: 'Penne with basil pesto and parmesan',
        descriptionDe: 'Penne mit Basilikum-Pesto und Parmesan',
        price: 10.50,
        sortOrder: 4,
        isActive: true,
        isAvailable: true,
        preparationTime: 12,
        calories: 690,
        allergens: ['Gluten', 'Eggs', 'Milk', 'Nuts'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pasta-marinara' },
      update: {},
      create: {
        id: 'pasta-marinara',
        categoryId: pastaCategory.id,
        name: 'Spaghetti Marinara',
        nameDe: 'Spaghetti Marinara',
        description: 'Spaghetti with tomato and garlic sauce',
        descriptionDe: 'Spaghetti mit Tomaten-Knoblauch-Sauce',
        price: 9.00,
        sortOrder: 5,
        isActive: true,
        isAvailable: true,
        preparationTime: 12,
        calories: 520,
        allergens: ['Gluten', 'Eggs'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'pasta-lasagna' },
      update: {},
      create: {
        id: 'pasta-lasagna',
        categoryId: pastaCategory.id,
        name: 'Lasagna',
        nameDe: 'Lasagne',
        description: 'Classic lasagna with meat sauce and bechamel',
        descriptionDe: 'Klassische Lasagne mit Fleischsauce und Béchamel',
        price: 12.50,
        sortOrder: 6,
        isActive: true,
        isAvailable: true,
        preparationTime: 20,
        calories: 850,
        allergens: ['Gluten', 'Eggs', 'Milk'],
      },
    }),
  ]);
  console.log('✅ Pastas created:', pastas.length);

  // Salads Products
  const saladsCategory = categories.find(c => c.id === 'salads')!;
  const salads = await Promise.all([
    prisma.product.upsert({
      where: { id: 'salad-caesar' },
      update: {},
      create: {
        id: 'salad-caesar',
        categoryId: saladsCategory.id,
        name: 'Caesar Salad',
        nameDe: 'Caesar Salat',
        description: 'Romaine lettuce, croutons, parmesan, and caesar dressing',
        descriptionDe: 'Römersalat, Croutons, Parmesan und Caesar-Dressing',
        price: 8.50,
        sortOrder: 1,
        isActive: true,
        isAvailable: true,
        preparationTime: 8,
        calories: 450,
        allergens: ['Eggs', 'Milk', 'Gluten', 'Fish'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'salad-greek' },
      update: {},
      create: {
        id: 'salad-greek',
        categoryId: saladsCategory.id,
        name: 'Greek Salad',
        nameDe: 'Griechischer Salat',
        description: 'Tomatoes, cucumber, olives, feta cheese, and olive oil',
        descriptionDe: 'Tomaten, Gurken, Oliven, Feta-Käse und Olivenöl',
        price: 8.00,
        sortOrder: 2,
        isActive: true,
        isAvailable: true,
        preparationTime: 8,
        calories: 380,
        allergens: ['Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'salad-chicken' },
      update: {},
      create: {
        id: 'salad-chicken',
        categoryId: saladsCategory.id,
        name: 'Chicken Salad',
        nameDe: 'Hähnchen Salat',
        description: 'Mixed greens, grilled chicken, tomatoes, and vinaigrette',
        descriptionDe: 'Gemischter Salat, gegrilltes Hähnchen, Tomaten und Vinaigrette',
        price: 9.50,
        sortOrder: 3,
        isActive: true,
        isAvailable: true,
        preparationTime: 10,
        calories: 420,
        allergens: ['Eggs'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'salad-quinoa' },
      update: {},
      create: {
        id: 'salad-quinoa',
        categoryId: saladsCategory.id,
        name: 'Quinoa Salad',
        nameDe: 'Quinoa Salat',
        description: 'Quinoa, vegetables, and lemon dressing',
        descriptionDe: 'Quinoa, Gemüse und Zitronen-Dressing',
        price: 9.00,
        sortOrder: 4,
        isActive: true,
        isAvailable: true,
        preparationTime: 8,
        calories: 350,
        allergens: [],
      },
    }),
    prisma.product.upsert({
      where: { id: 'salad-tuna' },
      update: {},
      create: {
        id: 'salad-tuna',
        categoryId: saladsCategory.id,
        name: 'Tuna Salad',
        nameDe: 'Thunfisch Salat',
        description: 'Mixed greens, tuna, corn, and yogurt dressing',
        descriptionDe: 'Gemischter Salat, Thunfisch, Mais und Joghurt-Dressing',
        price: 10.00,
        sortOrder: 5,
        isActive: true,
        isAvailable: true,
        preparationTime: 8,
        calories: 380,
        allergens: ['Fish', 'Eggs', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'salad-veggie' },
      update: {},
      create: {
        id: 'salad-veggie',
        categoryId: saladsCategory.id,
        name: 'Veggie Salad',
        nameDe: 'Gemüse Salat',
        description: 'Mixed vegetables, avocado, and balsamic dressing',
        descriptionDe: 'Gemischtes Gemüse, Avocado und Balsamico-Dressing',
        price: 8.50,
        sortOrder: 6,
        isActive: true,
        isAvailable: true,
        preparationTime: 8,
        calories: 320,
        allergens: [],
      },
    }),
  ]);
  console.log('✅ Salads created:', salads.length);

  // Desserts Products
  const dessertsCategory = categories.find(c => c.id === 'desserts')!;
  const desserts = await Promise.all([
    prisma.product.upsert({
      where: { id: 'dessert-tiramisu' },
      update: {},
      create: {
        id: 'dessert-tiramisu',
        categoryId: dessertsCategory.id,
        name: 'Tiramisu',
        nameDe: 'Tiramisu',
        description: 'Classic Italian dessert with mascarpone and espresso',
        descriptionDe: 'Klassisches italienisches Dessert mit Mascarpone und Espresso',
        price: 5.50,
        sortOrder: 1,
        isActive: true,
        isAvailable: true,
        preparationTime: 5,
        calories: 420,
        allergens: ['Eggs', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'dessert-cheesecake' },
      update: {},
      create: {
        id: 'dessert-cheesecake',
        categoryId: dessertsCategory.id,
        name: 'Cheesecake',
        nameDe: 'Käsekuchen',
        description: 'New York style cheesecake with berry compote',
        descriptionDe: 'New York Style Käsekuchen mit Beerenkompott',
        price: 5.00,
        sortOrder: 2,
        isActive: true,
        isAvailable: true,
        preparationTime: 5,
        calories: 450,
        allergens: ['Eggs', 'Milk', 'Gluten'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'dessert-pudding' },
      update: {},
      create: {
        id: 'dessert-pudding',
        categoryId: dessertsCategory.id,
        name: 'Chocolate Pudding',
        nameDe: 'Schokoladenpudding',
        description: 'Rich chocolate pudding with whipped cream',
        descriptionDe: 'Reichhaltiger Schokoladenpudding mit Sahne',
        price: 4.00,
        sortOrder: 3,
        isActive: true,
        isAvailable: true,
        preparationTime: 5,
        calories: 380,
        allergens: ['Eggs', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'dessert-icecream' },
      update: {},
      create: {
        id: 'dessert-icecream',
        categoryId: dessertsCategory.id,
        name: 'Ice Cream',
        nameDe: 'Eis',
        description: 'Three scoops of artisanal ice cream',
        descriptionDe: 'Drei Kugeln handgemachtes Eis',
        price: 4.50,
        sortOrder: 4,
        isActive: true,
        isAvailable: true,
        preparationTime: 3,
        calories: 320,
        allergens: ['Eggs', 'Milk', 'Nuts'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'dessert-creme-brulee' },
      update: {},
      create: {
        id: 'dessert-creme-brulee',
        categoryId: dessertsCategory.id,
        name: 'Crème Brûlée',
        nameDe: 'Crème Brûlée',
        description: 'Classic French custard with caramelized sugar top',
        descriptionDe: 'Klassische französische Creme mit karamellisierter Zuckerkruste',
        price: 5.50,
        sortOrder: 5,
        isActive: true,
        isAvailable: true,
        preparationTime: 5,
        calories: 350,
        allergens: ['Eggs', 'Milk'],
      },
    }),
    prisma.product.upsert({
      where: { id: 'dessert-fruit-salad' },
      update: {},
      create: {
        id: 'dessert-fruit-salad',
        categoryId: dessertsCategory.id,
        name: 'Fruit Salad',
        nameDe: 'Obstsalat',
        description: 'Fresh seasonal fruits with mint',
        descriptionDe: 'Frisches saisonales Obst mit Minze',
        price: 4.00,
        sortOrder: 6,
        isActive: true,
        isAvailable: true,
        preparationTime: 5,
        calories: 180,
        allergens: [],
      },
    }),
  ]);
  console.log('✅ Desserts created:', desserts.length);

  // Drinks Products
  const drinksCategory = categories.find(c => c.id === 'drinks')!;
  const drinks = await Promise.all([
    prisma.product.upsert({
      where: { id: 'drink-cola' },
      update: {},
      create: {
        id: 'drink-cola',
        categoryId: drinksCategory.id,
        name: 'Cola',
        nameDe: 'Cola',
        description: 'Classic cola drink',
        descriptionDe: 'Klassisches Cola-Getränk',
        price: 2.50,
        sortOrder: 1,
        isActive: true,
        isAvailable: true,
        preparationTime: 2,
        calories: 140,
        allergens: [],
      },
    }),
    prisma.product.upsert({
      where: { id: 'drink-fanta' },
      update: {},
      create: {
        id: 'drink-fanta',
        categoryId: drinksCategory.id,
        name: 'Fanta',
        nameDe: 'Fanta',
        description: 'Orange soda',
        descriptionDe: 'Orangenlimonade',
        price: 2.50,
        sortOrder: 2,
        isActive: true,
        isAvailable: true,
        preparationTime: 2,
        calories: 140,
        allergens: [],
      },
    }),
    prisma.product.upsert({
      where: { id: 'drink-sprite' },
      update: {},
      create: {
        id: 'drink-sprite',
        categoryId: drinksCategory.id,
        name: 'Sprite',
        nameDe: 'Sprite',
        description: 'Lemon-lime soda',
        descriptionDe: 'Zitronen-Limonade',
        price: 2.50,
        sortOrder: 3,
        isActive: true,
        isAvailable: true,
        preparationTime: 2,
        calories: 140,
        allergens: [],
      },
    }),
    prisma.product.upsert({
      where: { id: 'drink-water' },
      update: {},
      create: {
        id: 'drink-water',
        categoryId: drinksCategory.id,
        name: 'Mineral Water',
        nameDe: 'Mineralwasser',
        description: 'Sparkling mineral water',
        descriptionDe: 'Kohlensäurehaltiges Mineralwasser',
        price: 2.00,
        sortOrder: 4,
        isActive: true,
        isAvailable: true,
        preparationTime: 2,
        calories: 0,
        allergens: [],
      },
    }),
    prisma.product.upsert({
      where: { id: 'drink-juice' },
      update: {},
      create: {
        id: 'drink-juice',
        categoryId: drinksCategory.id,
        name: 'Orange Juice',
        nameDe: 'Orangensaft',
        description: 'Fresh orange juice',
        descriptionDe: 'Frischer Orangensaft',
        price: 3.50,
        sortOrder: 5,
        isActive: true,
        isAvailable: true,
        preparationTime: 3,
        calories: 110,
        allergens: [],
      },
    }),
    prisma.product.upsert({
      where: { id: 'drink-beer' },
      update: {},
      create: {
        id: 'drink-beer',
        categoryId: drinksCategory.id,
        name: 'Beer',
        nameDe: 'Bier',
        description: 'German pilsner beer',
        descriptionDe: 'Deutsches Pilsner Bier',
        price: 3.50,
        sortOrder: 6,
        isActive: true,
        isAvailable: true,
        preparationTime: 2,
        calories: 150,
        allergens: ['Gluten', 'Sulphites'],
      },
    }),
  ]);
  console.log('✅ Drinks created:', drinks.length);

  // ============================================================================
  // 4. CREATE PRODUCT IMAGES (placeholder URLs)
  // ============================================================================
  const allProducts = [...pizzas, ...burgers, ...doeners, ...pastas, ...salads, ...desserts, ...drinks];
  
  for (const product of allProducts) {
    await prisma.productImage.upsert({
      where: { id: `${product.id}-main` },
      update: {},
      create: {
        id: `${product.id}-main`,
        productId: product.id,
        url: `https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=500&q=80`,
        alt: `${product.nameDe}`,
        sortOrder: 0,
      },
    });
  }
  console.log('✅ Product images created:', allProducts.length);

  console.log('🎉 Seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
